<?xml version="1.0"?>

<package format="3">

  <name>hydro_sim</name>

  <version>0.0.1</version>

  <description>
    Underwater simulation environment for Gazebo Harmonic and ROS 2 Jazzy.
  </description>

  <maintainer email="thehuman130410@gmail.com">
    Raempest
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ros_gz_sim</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>